"""update user fields

Revision ID: 619d1296a64e
Revises: 
Create Date: 2026-09-13 17:01:55.524588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619d1296a64e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('hris_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('facility_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('lab_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('division_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('district_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('upazila_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('union_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['hris_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'union_id')
    op.drop_column('users', 'upazila_id')
    op.drop_column('users', 'district_id')
    op.drop_column('users', 'division_id')
    op.drop_column('users', 'lab_id')
    op.drop_column('users', 'facility_id')
    op.drop_column('users', 'hris_id')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'status')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###